# === 📄 PDF 生成函数 (这是 VIP 功能的核心引擎，不能删！) ===
def create_pdf(image, text, filename):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # 1. 顶部标题 (居中, 大字)
    pdf.set_font("Arial", style='B', size=14)
    pdf.cell(190, 10, txt=f"VisionPrompter Report", ln=1, align='C')
    pdf.set_font("Arial", size=10)
    pdf.cell(190, 10, txt=f"File Reference: {filename}", ln=1, align='C')
    pdf.ln(5)
    
    # 2. 插入图片 (如果有的话)
    if image:
        try:
            with io.BytesIO() as output:
                image.save(output, format="JPEG")
                # 调整图片位置 (x=15, y=35) 和宽度 (w=180) 适应 A4
                pdf.image(output, x=15, y=35, w=180)
                pdf.ln(105) # 图片占位高度，防止文字盖住图片
        except:
            pdf.cell(190, 10, txt="[Image Processing Error]", ln=1)
            
    # 3. 提示词内容 (自动换行)
    pdf.set_font("Arial", size=11)
    safe_text = text.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 8, safe_text)
    
    # 4. === 💎 底部签名 (防伪水印) ===
    pdf.ln(15)
    # 画一条浅灰色的横线
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    # 自动抓取当前用户身份
    current_user = st.session_state.get('user_email', '')
    if not current_user:
         # 如果是 VIP 码登录且没填邮箱，显示尊贵身份
         current_user = "Verified VIP Member"

    pdf.set_font("Arial", size=8, style='I')
    pdf.set_text_color(128, 128, 128) # 灰色字体显得高级
    
    # 这里会自动把 Cikgu Lai 或者用户的邮箱填进去
    footer_text = f"Generated by VisionPrompter AI | Licensed to: {current_user} | Date: {time.strftime('%Y-%m-%d')}"
    
    pdf.cell(0, 10, txt=footer_text, ln=1, align='R')
    return pdf.output(dest='S').encode('latin-1')