# app.py
# Lai's Lab V9.20 - 界面核心 (Final Launch Version)

import streamlit as st
import time
import base64
import os
from fpdf import FPDF 

import logic_core as lc 
import data_matrix as dm

# ==========================================
# 1. 页面配置 & CSS
# ==========================================
st.set_page_config(page_title="Lai's Lab AI", page_icon="🧬", layout="wide", initial_sidebar_state="expanded")

st.markdown("""
<style>
    #MainMenu {visibility: hidden;} footer {visibility: hidden;} header {visibility: hidden;}
    div[data-testid="stDecoration"] {visibility: hidden; height: 0px;}
    .block-container {padding-top: 1rem !important; padding-bottom: 5rem;}
    
    .promo-box {
        background-color: #fff0f0; border: 1px solid #ffcdd2; color: #d32f2f;
        padding: 10px 15px; border-radius: 8px; font-size: 15px; margin-bottom: 25px;
        display: flex; align-items: center; gap: 10px;
    }
    .promo-price {font-weight: bold; font-size: 18px; color: #e53935;}
    .promo-old {text-decoration: line-through; color: #9e9e9e; font-size: 13px;}
    
    a {text-decoration: none !important; color: #666;} 
    a:hover {text-decoration: underline !important; color: #333;}
    
    .lost-key-link {text-align: center; margin-top: 15px; font-size: 13px; color: #888;}
    .lost-key-link a {color: #666; border-bottom: 1px dashed #ccc;}
    .lost-key-link a:hover {color: #d32f2f; border-bottom: 1px solid #d32f2f;}

    section[data-testid="stSidebar"] .block-container {padding-top: 2rem;}
</style>
""", unsafe_allow_html=True)

# 🔐 Secrets 注入 (完整版)
if "general" in st.secrets:
    s = st.secrets["general"]
    # 邮件
    if "email_app_password" in s: lc.CONFIG["EMAIL_APP_PASSWORD"] = s["email_app_password"]
    if "email_sender" in s: lc.CONFIG["EMAIL_SENDER_ADDRESS"] = s["email_sender"]
    if "email_admin" in s: lc.CONFIG["EMAIL_ADMIN_ADDRESS"] = s["email_admin"]
    # 支付与验证
    if "lemonsqueezy_key" in s: lc.CONFIG["LEMONSQUEEZY_API_KEY"] = s["lemonsqueezy_key"]
    if "master_key" in s: lc.CONFIG["MASTER_KEY"] = s["master_key"]
    # Airtable
    if "airtable_key" in s: lc.CONFIG["AIRTABLE_API_KEY"] = s["airtable_key"]
    if "airtable_base_id" in s: lc.CONFIG["AIRTABLE_BASE_ID"] = s["airtable_base_id"]
    if "airtable_table_tickets" in s: lc.CONFIG["AIRTABLE_TABLE_TICKETS"] = s["airtable_table_tickets"]
    if "airtable_table_users" in s: lc.CONFIG["AIRTABLE_TABLE_USERS"] = s["airtable_table_users"]

# Session State
if 'logged_in' not in st.session_state: st.session_state.logged_in = False
if 'user_tier' not in st.session_state: st.session_state.user_tier = "Guest"
if 'user_email' not in st.session_state: st.session_state.user_email = ""
if 'language' not in st.session_state: st.session_state.language = "English"
if 'daily_usage' not in st.session_state: st.session_state.daily_usage = 0

# ==========================================
# 2. 辅助函数
# ==========================================
def render_download_button(text, filename="prompt.txt"):
    b64 = base64.b64encode(text.encode()).decode()
    href = f'<a href="data:file/txt;base64,{b64}" download="{filename}" style="background:#f0f2f6; padding:8px 12px; border-radius:5px; color:#333; text-decoration:none; font-size:14px;">📄 Download TXT</a>'
    st.markdown(href, unsafe_allow_html=True)

def create_pdf(content, role, mode):
    pdf = FPDF()
    pdf.add_page(); pdf.set_auto_page_break(auto=True, margin=15)
    font_path = "font.ttf"
    if os.path.exists(font_path):
        pdf.add_font('CustomFont', '', font_path, uni=True); pdf.set_font("CustomFont", size=12)
    else:
        pdf.set_font("Arial", size=12); content = content.encode('latin-1', 'replace').decode('latin-1') 
    pdf.set_font_size(16); pdf.cell(0, 10, txt=f"Lai's Lab Export - {role} / {mode}", ln=True, align='C'); pdf.ln(10)
    pdf.set_font_size(12); pdf.multi_cell(0, 10, txt=content); pdf.ln(20)
    pdf.set_font_size(10); pdf.cell(0, 10, txt="Generated by Lai's Lab Enterprise Engine", ln=True, align='C')
    return pdf.output(dest="S").encode("latin-1")

def render_footer():
    st.markdown("---")
    disclaimer = "Generative AI can make mistakes; please verify important information. Users are solely responsible for how they use the generated content. Lai's Lab assumes no liability for actions taken based on these outputs."
    footer = f'<div style="text-align: center; font-family: sans-serif; padding-bottom: 30px;"><p style="font-size: 12px; color: #666; margin-bottom: 15px;"><a href="#" style="color:#666;margin:0 10px;">Privacy Policy</a> | <a href="#" style="color:#666;margin:0 10px;">Terms</a> | <a href="mailto:support@laislab.com" style="color:#666;margin:0 10px;">Support</a></p><div style="font-size: 11px; color: #999; line-height: 1.4; max-width: 800px; margin: 0 auto 20px auto;">{disclaimer}</div><p style="font-size: 12px; color: #444;">© 2025 <b>Lai\'s Lab</b> <span style="color: #ccc;">|</span> System V9.20 Enterprise</p></div>'
    st.markdown(footer, unsafe_allow_html=True)

def logout():
    lc.perform_logout(); st.session_state.clear(); st.rerun()

# ==========================================
# 3. 登录界面
# ==========================================
def show_login_page():
    col1, col2 = st.columns([1, 1.3])
    with col1:
        if os.path.exists("logo.png"): st.image("logo.png", width=120)
        else: st.markdown("## 🧬 Lai's Lab")
        st.title("PromptLab AI V9.20"); st.caption("The Ultimate Enterprise Prompt Engine"); st.markdown("---")
        st.markdown('<div class="promo-box"><span>🔥 <b>Limited Deal:</b> Lifetime Pro Access for</span><span class="promo-price">$12.90</span><span class="promo-old">$39.90</span></div>', unsafe_allow_html=True)
        st.subheader("🔓 Login / Access")
        t1, t2 = st.tabs(["👤 Guest Trial", "💎 Activate Pro"])
        with t1:
            email = st.text_input("Enter Email", placeholder="you@example.com")
            if st.button("🚀 Start Free Trial", use_container_width=True):
                if "@" in email: st.session_state.user_email = email; st.session_state.user_tier = "Guest"; st.session_state.logged_in = True; st.rerun()
                else: st.warning("Invalid Email")
        with t2:
            p_email = st.text_input("Pro Email", placeholder="Email used for purchase")
            l_key = st.text_input("License Key", type="password", placeholder="Enter your license key")
            if st.button("💎 Activate License", type="primary", use_container_width=True):
                with st.spinner("Verifying License..."):
                    status = lc.check_user_tier(p_email, l_key)
                    if status == "Pro": st.session_state.user_email = p_email; st.session_state.user_tier = "Pro"; st.session_state.logged_in = True; st.balloons(); time.sleep(1); st.rerun()
                    else: st.error("❌ Invalid or Expired License Key.")
            
            st.markdown("""
            <div class="lost-key-link">
                <a href="https://app.lemonsqueezy.com/my-orders" target="_blank">
                    🔒 Forgot or Lost your License Key?
                </a>
            </div>
            """, unsafe_allow_html=True)

    with col2:
        st.subheader("🆚 Compare Plans")
        st.markdown("""<style>.cmp-table{width:100%;border-collapse:collapse;font-size:14px;margin-top:10px}.cmp-table th{text-align:left;padding:12px 8px;border-bottom:2px solid #eee;color:#555}.cmp-table td{padding:10px 8px;border-bottom:1px solid #f5f5f5;color:#666}.pro-h{background-color:#f0f7ff;color:#0277bd;font-weight:600}.check{color:#2e7d32;font-weight:bold}.cross{color:#c62828;font-weight:bold}</style><table class="cmp-table"><thead><tr><th>Feature</th><th>Guest</th><th class="pro-h">💎 PRO Lifetime</th></tr></thead><tbody><tr><td>AI Engine</td><td>Standard</td><td class="pro-h">🚀 Turbo Mode</td></tr><tr><td>Daily Limit</td><td>🔒 5 / Day</td><td class="pro-h">✅ 1000 / Day</td></tr><tr><td>Modes</td><td>🔒 1 Mode</td><td class="pro-h">✅ All 18 Modes</td></tr><tr><td>Language</td><td>🔒 3 (Basic)</td><td class="pro-h">✅ 15 Global</td></tr><tr><td>Support</td><td>Standard</td><td class="pro-h">⚡ Priority</td></tr></tbody></table>""", unsafe_allow_html=True)
        st.info("💡 Join 10,000+ Educators & Creators today.")
    render_footer()

# ==========================================
# 4. 主工作台
# ==========================================
def show_main_app():
    curr_lang = st.session_state.language
    ui = dm.LANG_MAP.get(curr_lang, dm.LANG_MAP["default"])

    # Sidebar
    with st.sidebar:
        if os.path.exists("logo.png"): st.image("logo.png", width=80)
        else: st.markdown(f"### {ui['sidebar_title']}")
        
        tier_icon = "💎" if st.session_state.user_tier == "Pro" else "👤"
        tier_text = ui['plan_pro'] if st.session_state.user_tier == "Pro" else ui['plan_guest']
        st.caption(f"{tier_icon} {tier_text}"); st.caption(f"📧 {st.session_state.user_email}")
        
        _, _, max_limit = lc.check_daily_limit_by_email(st.session_state.user_email, st.session_state.user_tier, st.session_state.daily_usage)
        pval = 0 if max_limit == 0 else st.session_state.daily_usage / max_limit
        st.progress(min(pval, 1.0)); st.caption(f"{ui['usage']}: {st.session_state.daily_usage} / {max_limit}")
        st.divider()

        available_langs = dm.LANG_OPTIONS_PRO if st.session_state.user_tier == "Pro" else dm.LANG_OPTIONS_GUEST
        idx = available_langs.index(curr_lang) if curr_lang in available_langs else 0
        sel_lang = st.selectbox(ui['lang'], available_langs, index=idx)
        if sel_lang != st.session_state.language: st.session_state.language = sel_lang; st.rerun()

        role_list = list(dm.ROLES_CONFIG.keys())
        sel_role = st.selectbox(ui['role'], role_list)
        st.divider()

        with st.expander(ui['faq']):
            for item in dm.FAQ_LIST: st.markdown(f"- {item}")
        with st.expander(ui['support']):
            t_type = st.selectbox("Type", ui['ticket_types'])
            t_sub = st.text_input("Subject")
            intercept, msg = lc.smart_intercept(t_sub)
            if intercept: st.warning(msg)
            t_msg = st.text_area("Msg", height=80)
            if st.button("Submit Ticket"):
                if t_sub and t_msg:
                    tid = int(time.time())
                    lc.log_ticket_to_airtable(tid, st.session_state.user_email, st.session_state.user_tier, f"[{t_type}] {t_sub}")
                    lc.send_auto_reply_email(st.session_state.user_email, st.session_state.user_tier, tid, t_sub)
                    if st.session_state.user_tier == "Pro": st.success(f"💎 VIP Ticket #{tid} Sent!")
                    else: st.success(f"✅ Ticket #{tid} Sent!")
                else: st.error("Fill all fields")
        st.divider(); 
        if st.button(ui['logout']): logout()

    # Main Area
    st.header(f"{sel_role} Workspace")
    modes = list(dm.ROLES_CONFIG[sel_role].keys())
    sel_mode = st.selectbox(ui['mode'], modes)
    
    is_locked = lc.check_mode_lock(st.session_state.user_tier, sel_mode)
    if is_locked:
        st.error(ui['lock_msg']); st.info(ui['lock_desc'])
        st.link_button(ui['buy_btn'], "https://laislab.lemonsqueezy.com/buy", type="primary")
    else:
        opts = dm.ROLES_CONFIG[sel_role][sel_mode]
        opt_labels = [o["label"] for o in opts]
        sel_opt_label = st.selectbox(ui['action'], opt_labels)
        
        role_tones = dm.ROLE_TONES.get(sel_role, dm.DEFAULT_TONES)
        selected_tone = st.selectbox(ui.get('tone', "🗣️ Tone / Style"), role_tones)
        
        ph_text = "Describe exactly what you need..." if "Custom" in sel_opt_label else ui['input_ph']
        user_input = st.text_area(ui['input_label'], placeholder=ph_text, height=150)
        
        if st.button(ui['generate'], type="primary", use_container_width=True):
            if not user_input: st.warning("No input provided.")
            elif st.session_state.daily_usage >= max_limit and st.session_state.user_tier != "Pro": st.error("Limit Reached")
            else:
                st.session_state.daily_usage += 1
                out = st.empty()
                if st.session_state.user_tier == "Guest":
                    bar = st.progress(0); 
                    for i in range(50): time.sleep(0.02); bar.progress(i*2)
                    bar.empty()
                else:
                    with st.spinner("⚡ Pro Generating..."): time.sleep(0.5)
                
                # ✅ 调用真实 PASEC 生成器
                final_res = lc.generate_pasec_prompt(sel_role, sel_mode, sel_opt_label, user_input, st.session_state.user_tier, st.session_state.language, selected_tone)
                
                out.markdown(f"### {ui['result']}")
                st.text_area("Result", value=final_res, height=450)
                
                c1, c2, c3 = st.columns(3)
                with c1: render_download_button(final_res)
                with c2: st.link_button("🎨 Midjourney", "https://www.midjourney.com")
                with c3: st.link_button("💬 WhatsApp", "https://wa.me/")
                
                if st.session_state.user_tier == "Pro":
                    st.divider(); st.markdown("#### 💎 Pro Export")
                    pdf_data = create_pdf(final_res, sel_role, sel_mode)
                    st.download_button("📕 Download PDF", pdf_data, "report.pdf", "application/pdf", use_container_width=True)
    render_footer()

if __name__ == "__main__":
    if st.session_state.logged_in: show_main_app()
    else: show_login_page()
