# dm_ui.py
# Lai's Lab UI Module - COMMERCIAL V9.38
# Features: Updated Slogan "Your AI Automated Prompt Engineer" in 16 Languages

UI_BUNDLE = {
    # 1. English
    "English": {
        "title": "PromptLab AI",
        "subtitle": "Your AI Automated Prompt Engineer",
        "role": "Select Persona", "mode": "Select Mode", "tone": "Select Tone",
        "input_label": "Enter your topic, content, or paste text here...",
        "btn_submit": "✨ Generate Content",
        "btn_copy": "📋 Copy",
        "btn_clear": "🗑️ Clear",
        "tab_main": "Generative AI",
        "tab_history": "History",
        "tab_upgrade": "Upgrade Pro",
        "tab_help": "Help & Support",
        "tbl_head": ["Feature Comparison", "Guest (Free)", "Pro (Paid)"],
        "upgrade_title": "Unlock Professional Power",
        "upgrade_btn": "Get Pro Key",
        # Required for app.py
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "Guest Plan", "plan_pro": "Pro Plan",
        "usage": "Daily Usage", "lang": "Interface Language",
        "faq_title": "Support & FAQ", "quick_ans": "Quick Answers", "sel_topic": "Select Topic",
        "submit_ticket": "Submit Ticket", "type_lbl": "Ticket Type",
        "issue_lbl": "Describe issue or press Enter to search...",
        "send_btn": "Submit Ticket", "logout": "Reset / Logout",
        "action": "Select Action", "out_lang_lbl": "Output Language", "tone_lbl": "Tone of Voice",
        "generate": "✨ Generate Content",
        "lock_msg": "This is a Pro Feature. Please upgrade to access.",
        "buy_btn": "👉 Upgrade to Pro Now",
        "result": "Generated Result",
        "ad_copy": "1. Copy Result", "ad_connect": "2. Refine in AI Tools",
        "ad_social": "3. Share to Social", "ad_manual": "4. Manual Post",
        "ad_download": "5. Save Files", "ad_locked": "Pro Only"
    },
    
    "简体中文": {
        "title": "PromptLab AI",
        "subtitle": "您的 AI 自动化提示词工程师",
        "role": "选择角色", "mode": "选择模式", "tone": "选择语调",
        "input_label": "请输入主题、内容或粘贴文本...",
        "btn_submit": "✨ 生成内容",
        "btn_copy": "📋 复制",
        "btn_clear": "🗑️ 清空",
        "tab_main": "AI 生成",
        "tab_history": "历史记录",
        "tab_upgrade": "升级 Pro",
        "tab_help": "帮助中心",
        "tbl_head": ["功能权益对比", "游客 (免费)", "Pro (付费)"],
        "upgrade_title": "解锁专业版功能",
        "upgrade_btn": "获取激活码",
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "游客版", "plan_pro": "专业版",
        "usage": "今日用量", "lang": "界面语言",
        "faq_title": "帮助与支持", "quick_ans": "快速问答", "sel_topic": "选择话题",
        "submit_ticket": "提交工单", "type_lbl": "工单类型",
        "issue_lbl": "描述问题或回车搜索答案...",
        "send_btn": "提交工单", "logout": "重置 / 登出",
        "action": "选择具体任务", "out_lang_lbl": "输出语言", "tone_lbl": "语气语调",
        "generate": "✨ 立即生成",
        "lock_msg": "这是 Pro 专业版功能，请升级解锁。",
        "buy_btn": "👉 立即升级 Pro",
        "result": "生成结果",
        "ad_copy": "1. 一键复制", "ad_connect": "2. AI 工具精修",
        "ad_social": "3. 社交分享", "ad_manual": "4. 手动发布",
        "ad_download": "5. 保存文件", "ad_locked": "仅限 Pro"
    },

    "繁體中文": {
        "title": "PromptLab AI",
        "subtitle": "您的 AI 自動化提示詞工程師",
        "role": "選擇角色", "mode": "選擇模式", "tone": "選擇語調",
        "input_label": "請輸入主題、內容或貼上文本...",
        "btn_submit": "✨ 生成內容",
        "btn_copy": "📋 複製",
        "btn_clear": "🗑️ 清空",
        "tab_main": "AI 生成",
        "tab_history": "歷史記錄",
        "tab_upgrade": "升級 Pro",
        "tab_help": "幫助中心",
        "tbl_head": ["功能權益對比", "遊客 (免費)", "Pro (付費)"],
        "upgrade_title": "解鎖專業版功能",
        "upgrade_btn": "獲取激活碼",
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "遊客版", "plan_pro": "專業版",
        "usage": "今日用量", "lang": "介面語言",
        "faq_title": "幫助與支援", "quick_ans": "快速問答", "sel_topic": "選擇話題",
        "submit_ticket": "提交工單", "type_lbl": "工單類型",
        "issue_lbl": "描述問題或按 Enter 搜尋...",
        "send_btn": "提交工單", "logout": "重置 / 登出",
        "action": "選擇具體任務", "out_lang_lbl": "輸出語言", "tone_lbl": "語氣語調",
        "generate": "✨ 立即生成",
        "lock_msg": "這是 Pro 專業版功能，請升級解鎖。",
        "buy_btn": "👉 立即升級 Pro",
        "result": "生成結果",
        "ad_copy": "1. 一鍵複製", "ad_connect": "2. AI 工具精修",
        "ad_social": "3. 社交分享", "ad_manual": "4. 手動發佈",
        "ad_download": "5. 保存檔案", "ad_locked": "僅限 Pro"
    },

    "Bahasa Melayu": {
        "title": "PromptLab AI",
        "subtitle": "Jurutera Prompt AI Automasi Anda",
        "role": "Pilih Peranan", "mode": "Pilih Mod", "tone": "Nada Suara",
        "input_label": "Masukkan topik atau tampal teks di sini...",
        "btn_submit": "✨ Jana Kandungan",
        "btn_copy": "📋 Salin",
        "btn_clear": "🗑️ Padam",
        "tab_main": "AI Generatif",
        "tab_history": "Sejarah",
        "tab_upgrade": "Naik Taraf",
        "tab_help": "Bantuan",
        "tbl_head": ["Perbandingan Ciri", "Tetamu (Percuma)", "Pro (Berbayar)"],
        "upgrade_title": "Buka Kuasa Profesional",
        "upgrade_btn": "Dapatkan Kunci Pro",
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "Pelan Tetamu", "plan_pro": "Pelan Pro",
        "usage": "Penggunaan", "lang": "Bahasa Antaramuka",
        "faq_title": "Bantuan & Sokongan", "quick_ans": "Jawapan Pantas", "sel_topic": "Pilih Topik",
        "submit_ticket": "Hantar Tiket", "type_lbl": "Jenis Tiket",
        "issue_lbl": "Terangkan isu atau tekan Enter...",
        "send_btn": "Hantar", "logout": "Set Semula",
        "action": "Pilih Tindakan", "out_lang_lbl": "Bahasa Output", "tone_lbl": "Nada Suara",
        "generate": "✨ Jana Kandungan",
        "lock_msg": "Ini ciri Pro. Sila naik taraf.",
        "buy_btn": "👉 Dapatkan Pro",
        "result": "Hasil",
        "ad_copy": "1. Salin", "ad_connect": "2. Alat AI",
        "ad_social": "3. Kongsi Sosial", "ad_manual": "4. Manual",
        "ad_download": "5. Simpan Fail", "ad_locked": "Pro Sahaja"
    },

    "Español": {
        "title": "PromptLab AI",
        "subtitle": "Tu Ingeniero de Prompts AI Automatizado",
        "role": "Rol", "mode": "Modo", "tone": "Tono",
        "input_label": "Ingrese su tema o pegue texto aquí...",
        "btn_submit": "✨ Generar",
        "btn_copy": "📋 Copiar",
        "btn_clear": "🗑️ Borrar",
        "tab_main": "Generar",
        "tab_history": "Historial",
        "tab_upgrade": "Mejorar",
        "tab_help": "Ayuda",
        "tbl_head": ["Comparación", "Invitado", "Pro (Pago)"],
        "upgrade_title": "Desbloquear Pro",
        "upgrade_btn": "Obtener Clave",
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "Plan Invitado", "plan_pro": "Plan Pro",
        "usage": "Uso Diario", "lang": "Idioma Interfaz",
        "faq_title": "Ayuda y FAQ", "quick_ans": "Respuestas Rápidas", "sel_topic": "Seleccionar Tema",
        "submit_ticket": "Enviar Ticket", "type_lbl": "Tipo de Ticket",
        "issue_lbl": "Describa el problema o presione Enter...",
        "send_btn": "Enviar", "logout": "Reiniciar",
        "action": "Seleccionar Acción", "out_lang_lbl": "Idioma de Salida", "tone_lbl": "Tono de Voz",
        "generate": "✨ Generar Contenido",
        "lock_msg": "Función Pro. Por favor actualice.",
        "buy_btn": "👉 Obtener Pro Ahora",
        "result": "Resultado Generado",
        "ad_copy": "1. Copiar", "ad_connect": "2. Herramientas AI",
        "ad_social": "3. Compartir", "ad_manual": "4. Publicar",
        "ad_download": "5. Guardar Archivos", "ad_locked": "Solo Pro"
    },

    "日本語": {
        "title": "PromptLab AI",
        "subtitle": "あなたのAI自動プロンプトエンジニア",
        "role": "役割選択", "mode": "モード", "tone": "口調",
        "input_label": "トピックを入力またはテキストを貼り付け...",
        "btn_submit": "✨ 生成する",
        "btn_copy": "📋 コピー",
        "btn_clear": "🗑️ 消去",
        "tab_main": "AI生成",
        "tab_history": "履歴",
        "tab_upgrade": "Proへ",
        "tab_help": "ヘルプ",
        "tbl_head": ["機能比較", "ゲスト (無料)", "Pro (有料)"],
        "upgrade_title": "Pro版を解除",
        "upgrade_btn": "キーを入手",
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "ゲストプラン", "plan_pro": "Proプラン",
        "usage": "本日の使用量", "lang": "表示言語",
        "faq_title": "ヘルプとサポート", "quick_ans": "クイックQA", "sel_topic": "トピックを選択",
        "submit_ticket": "チケット送信", "type_lbl": "チケット種類",
        "issue_lbl": "問題を記述またはEnterで検索...",
        "send_btn": "送信する", "logout": "リセット/ログアウト",
        "action": "アクション選択", "out_lang_lbl": "出力言語", "tone_lbl": "口調・トーン",
        "generate": "✨ コンテンツ生成",
        "lock_msg": "これはPro機能です。アップグレードしてください。",
        "buy_btn": "👉 今すぐProへ",
        "result": "生成結果",
        "ad_copy": "1. コピー", "ad_connect": "2. AIツール連携",
        "ad_social": "3. シェア", "ad_manual": "4. 手動投稿",
        "ad_download": "5. 保存", "ad_locked": "Pro限定"
    },

    "한국어": {
        "title": "PromptLab AI",
        "subtitle": "당신의 AI 자동 프롬프트 엔지니어",
        "role": "역할 선택", "mode": "모드", "tone": "어조",
        "input_label": "주제를 입력하거나 텍스트를 붙여넣으세요...",
        "btn_submit": "✨ 생성하기",
        "btn_copy": "📋 복사",
        "btn_clear": "🗑️ 지우기",
        "tab_main": "AI 생성",
        "tab_history": "기록",
        "tab_upgrade": "Pro 업그레이드",
        "tab_help": "도움말",
        "tbl_head": ["기능 비교", "게스트 (무료)", "Pro (유료)"],
        "upgrade_title": "Pro 잠금 해제",
        "upgrade_btn": "키 구매하기",
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "게스트 플랜", "plan_pro": "Pro 플랜",
        "usage": "일일 사용량", "lang": "인터페이스 언어",
        "faq_title": "고객 지원", "quick_ans": "빠른 답변", "sel_topic": "주제 선택",
        "submit_ticket": "티켓 제출", "type_lbl": "티켓 유형",
        "issue_lbl": "문제를 설명하거나 Enter를 눌러 검색...",
        "send_btn": "제출하기", "logout": "초기화 / 로그아웃",
        "action": "작업 선택", "out_lang_lbl": "출력 언어", "tone_lbl": "어조",
        "generate": "✨ 콘텐츠 생성",
        "lock_msg": "Pro 기능입니다. 업그레이드해주세요.",
        "buy_btn": "👉 Pro 업그레이드",
        "result": "생성 결과",
        "ad_copy": "1. 복사", "ad_connect": "2. AI 도구",
        "ad_social": "3. 공유", "ad_manual": "4. 수동 게시",
        "ad_download": "5. 파일 저장", "ad_locked": "Pro 전용"
    },

    "Français": {
        "title": "PromptLab AI",
        "subtitle": "Votre Ingénieur de Prompt AI Automatisé",
        "role": "Rôle", "mode": "Mode", "tone": "Ton",
        "input_label": "Entrez votre sujet ou collez du texte...",
        "btn_submit": "✨ Générer",
        "btn_copy": "📋 Copier",
        "btn_clear": "🗑️ Effacer",
        "tab_main": "Générer",
        "tab_history": "Historique",
        "tab_upgrade": "Upgrade",
        "tab_help": "Aide",
        "tbl_head": ["Comparaison", "Invité (Gratuit)", "Pro (Payant)"],
        "upgrade_title": "Débloquer Pro",
        "upgrade_btn": "Obtenir Clé",
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "Plan Invité", "plan_pro": "Plan Pro",
        "usage": "Usage Quotidien", "lang": "Langue",
        "faq_title": "Aide & Support", "quick_ans": "Réponses Rapides", "sel_topic": "Choisir Sujet",
        "submit_ticket": "Soumettre Ticket", "type_lbl": "Type de Ticket",
        "issue_lbl": "Décrivez le problème ou Entrée...",
        "send_btn": "Envoyer", "logout": "Réinitialiser",
        "action": "Choisir Action", "out_lang_lbl": "Langue de Sortie", "tone_lbl": "Ton",
        "generate": "✨ Générer",
        "lock_msg": "Fonctionnalité Pro. Veuillez mettre à jour.",
        "buy_btn": "👉 Obtenir Pro",
        "result": "Résultat",
        "ad_copy": "1. Copier", "ad_connect": "2. Outils IA",
        "ad_social": "3. Partager", "ad_manual": "4. Manuel",
        "ad_download": "5. Enregistrer", "ad_locked": "Pro Uniquement"
    },

    "Deutsch": {
        "title": "PromptLab AI",
        "subtitle": "Ihr automatisierter KI-Prompt-Ingenieur",
        "role": "Rolle", "mode": "Modus", "tone": "Tonfall",
        "input_label": "Thema eingeben oder Text einfügen...",
        "btn_submit": "✨ Generieren",
        "btn_copy": "📋 Kopieren",
        "btn_clear": "🗑️ Löschen",
        "tab_main": "Generieren",
        "tab_history": "Verlauf",
        "tab_upgrade": "Upgrade",
        "tab_help": "Hilfe",
        "tbl_head": ["Vergleich", "Gast (Gratis)", "Pro (Bezahlt)"],
        "upgrade_title": "Pro Freischalten",
        "upgrade_btn": "Key Kaufen",
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "Gast Plan", "plan_pro": "Pro Plan",
        "usage": "Nutzung", "lang": "Sprache",
        "faq_title": "Hilfe & Support", "quick_ans": "Schnellantworten", "sel_topic": "Thema wählen",
        "submit_ticket": "Ticket senden", "type_lbl": "Ticket-Typ",
        "issue_lbl": "Problem beschreiben oder Enter...",
        "send_btn": "Senden", "logout": "Reset / Logout",
        "action": "Aktion wählen", "out_lang_lbl": "Ausgabesprache", "tone_lbl": "Tonfall",
        "generate": "✨ Generieren",
        "lock_msg": "Dies ist ein Pro-Feature.",
        "buy_btn": "👉 Jetzt Pro holen",
        "result": "Ergebnis",
        "ad_copy": "1. Kopieren", "ad_connect": "2. KI-Tools",
        "ad_social": "3. Teilen", "ad_manual": "4. Manuell",
        "ad_download": "5. Speichern", "ad_locked": "Nur Pro"
    },

    "Italiano": {
        "title": "PromptLab AI",
        "subtitle": "Il tuo Ingegnere di Prompt AI Automatizzato",
        "role": "Ruolo", "mode": "Modalità", "tone": "Tono",
        "input_label": "Inserisci argomento o incolla testo...",
        "btn_submit": "✨ Genera",
        "btn_copy": "📋 Copia",
        "btn_clear": "🗑️ Cancella",
        "tab_main": "Genera",
        "tab_history": "Cronologia",
        "tab_upgrade": "Upgrade",
        "tab_help": "Aiuto",
        "tbl_head": ["Confronto", "Ospite", "Pro"],
        "upgrade_title": "Sblocca Pro",
        "upgrade_btn": "Ottieni Chiave",
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "Piano Ospite", "plan_pro": "Piano Pro",
        "usage": "Uso Giornaliero", "lang": "Lingua",
        "faq_title": "Aiuto & Supporto", "quick_ans": "Risposte Rapide", "sel_topic": "Scegli Argomento",
        "submit_ticket": "Invia Ticket", "type_lbl": "Tipo Ticket",
        "issue_lbl": "Descrivi il problema o premi Invio...",
        "send_btn": "Invia", "logout": "Reset / Logout",
        "action": "Scegli Azione", "out_lang_lbl": "Lingua Output", "tone_lbl": "Tono",
        "generate": "✨ Genera",
        "lock_msg": "Funzione Pro. Aggiorna per accedere.",
        "buy_btn": "👉 Passa a Pro",
        "result": "Risultato",
        "ad_copy": "1. Copia", "ad_connect": "2. Strumenti AI",
        "ad_social": "3. Condividi", "ad_manual": "4. Manuale",
        "ad_download": "5. Salva File", "ad_locked": "Solo Pro"
    },

    "Português": {
        "title": "PromptLab AI",
        "subtitle": "Seu Engenheiro de Prompt de IA Automatizado",
        "role": "Papel", "mode": "Modo", "tone": "Tom",
        "input_label": "Insira o tópico ou cole o texto...",
        "btn_submit": "✨ Gerar",
        "btn_copy": "📋 Copiar",
        "btn_clear": "🗑️ Limpar",
        "tab_main": "Gerar",
        "tab_history": "Histórico",
        "tab_upgrade": "Upgrade",
        "tab_help": "Ajuda",
        "tbl_head": ["Comparação", "Convidado", "Pro"],
        "upgrade_title": "Desbloquear Pro",
        "upgrade_btn": "Obter Chave",
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "Plano Visitante", "plan_pro": "Plano Pro",
        "usage": "Uso Diário", "lang": "Idioma",
        "faq_title": "Ajuda e Suporte", "quick_ans": "Respostas Rápidas", "sel_topic": "Escolher Tópico",
        "submit_ticket": "Enviar Ticket", "type_lbl": "Tipo de Ticket",
        "issue_lbl": "Descreva o problema ou Enter...",
        "send_btn": "Enviar", "logout": "Reiniciar",
        "action": "Escolher Ação", "out_lang_lbl": "Idioma de Saída", "tone_lbl": "Tom de Voz",
        "generate": "✨ Gerar Conteúdo",
        "lock_msg": "Recurso Pro. Por favor, atualize.",
        "buy_btn": "👉 Obter Pro",
        "result": "Resultado",
        "ad_copy": "1. Copiar", "ad_connect": "2. Ferramentas IA",
        "ad_social": "3. Partilhar", "ad_manual": "4. Manual",
        "ad_download": "5. Salvar", "ad_locked": "Apenas Pro"
    },

    "Русский": {
        "title": "PromptLab AI",
        "subtitle": "Ваш автоматизированный ИИ промпт-инженер",
        "role": "Роль", "mode": "Режим", "tone": "Тон",
        "input_label": "Введите тему или вставьте текст...",
        "btn_submit": "✨ Создать",
        "btn_copy": "📋 Копия",
        "btn_clear": "🗑️ Сброс",
        "tab_main": "Генерация",
        "tab_history": "История",
        "tab_upgrade": "Pro Версия",
        "tab_help": "Помощь",
        "tbl_head": ["Сравнение", "Гость (0₽)", "Pro (Платный)"],
        "upgrade_title": "Открыть Pro",
        "upgrade_btn": "Купить Ключ",
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "Гостевой план", "plan_pro": "Pro план",
        "usage": "Использование", "lang": "Язык интерфейса",
        "faq_title": "Помощь", "quick_ans": "Вопросы-ответы", "sel_topic": "Выберите тему",
        "submit_ticket": "Создать тикет", "type_lbl": "Тип тикета",
        "issue_lbl": "Опишите проблему или нажмите Enter...",
        "send_btn": "Отправить", "logout": "Сброс / Выход",
        "action": "Выберите действие", "out_lang_lbl": "Язык результата", "tone_lbl": "Тон",
        "generate": "✨ Создать",
        "lock_msg": "Это Pro функция. Обновитесь для доступа.",
        "buy_btn": "👉 Купить Pro",
        "result": "Результат",
        "ad_copy": "1. Копировать", "ad_connect": "2. ИИ инструменты",
        "ad_social": "3. Поделиться", "ad_manual": "4. Вручную",
        "ad_download": "5. Сохранить", "ad_locked": "Только Pro"
    },

    "Arabic": {
        "title": "PromptLab AI",
        "subtitle": "مهندس الأوامر الذكي الآلي الخاص بك",
        "role": "الدور", "mode": "الوضع", "tone": "النبرة",
        "input_label": "أدخل الموضوع أو الصق النص هنا...",
        "btn_submit": "✨ توليد",
        "btn_copy": "📋 نسخ",
        "btn_clear": "🗑️ مسح",
        "tab_main": "الذكاء الاصطناعي",
        "tab_history": "السجل",
        "tab_upgrade": "ترقية",
        "tab_help": "مساعدة",
        "tbl_head": ["مقارنة الميزات", "زائر (مجاني)", "Pro (مدفوع)"],
        "upgrade_title": "فتح الميزات الاحترافية",
        "upgrade_btn": "احصل على المفتاح",
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "خطة الزوار", "plan_pro": "خطة المحترفين",
        "usage": "الاستخدام اليومي", "lang": "لغة الواجهة",
        "faq_title": "الدعم والأسئلة", "quick_ans": "إجابات سريعة", "sel_topic": "اختر الموضوع",
        "submit_ticket": "إرسال تذكرة", "type_lbl": "نوع التذكرة",
        "issue_lbl": "صف المشكلة أو اضغط Enter...",
        "send_btn": "إرسال", "logout": "إعادة تعيين",
        "action": "اختر الإجراء", "out_lang_lbl": "لغة الإخراج", "tone_lbl": "نبرة الصوت",
        "generate": "✨ توليد المحتوى",
        "lock_msg": "هذه ميزة Pro. يرجى الترقية.",
        "buy_btn": "👉 احصل على Pro",
        "result": "النتيجة",
        "ad_copy": "1. نسخ", "ad_connect": "2. أدوات الذكاء",
        "ad_social": "3. مشاركة", "ad_manual": "4. نشر يدوي",
        "ad_download": "5. حفظ الملفات", "ad_locked": "للمحترفين فقط"
    },

    "Hindi": {
        "title": "PromptLab AI",
        "subtitle": "आपका एआई स्वचालित प्रॉम्प्ट इंजीनियर",
        "role": "भूमिका", "mode": "मोड", "tone": "लहज़ा",
        "input_label": "अपना विषय दर्ज करें या टेक्स्ट पेस्ट करें...",
        "btn_submit": "✨ उत्पन्न करें",
        "btn_copy": "📋 कॉपी",
        "btn_clear": "🗑️ साफ़ करें",
        "tab_main": "एआई जनरेट",
        "tab_history": "इतिहास",
        "tab_upgrade": "Pro अपग्रेड",
        "tab_help": "सहायता",
        "tbl_head": ["सुविधा तुलना", "अतिथि (मुफ़्त)", "Pro (भुगतान)"],
        "upgrade_title": "Pro अनलॉक करें",
        "upgrade_btn": "कुंजी प्राप्त करें",
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "अतिथि योजना", "plan_pro": "Pro योजना",
        "usage": "दैनिक उपयोग", "lang": "इंटरफ़ेस भाषा",
        "faq_title": "सहायता और प्रश्न", "quick_ans": "त्वरित उत्तर", "sel_topic": "विषय चुनें",
        "submit_ticket": "टिकट भेजें", "type_lbl": "टिकट प्रकार",
        "issue_lbl": "समस्या का वर्णन करें या Enter दबाएं...",
        "send_btn": "भेजें", "logout": "रीसेट / लॉगआउट",
        "action": "कार्य चुनें", "out_lang_lbl": "आउटपुट भाषा", "tone_lbl": "लहज़ा",
        "generate": "✨ सामग्री उत्पन्न करें",
        "lock_msg": "यह Pro सुविधा है। कृपया अपग्रेड करें।",
        "buy_btn": "👉 अभी Pro प्राप्त करें",
        "result": "परिणाम",
        "ad_copy": "1. कॉपी करें", "ad_connect": "2. एआई टूल्स",
        "ad_social": "3. साझा करें", "ad_manual": "4. मैनुअल",
        "ad_download": "5. सहेजें", "ad_locked": "केवल Pro"
    },

    "Thai": {
        "title": "PromptLab AI",
        "subtitle": "วิศวกรพร้อมท์ AI อัตโนมัติของคุณ",
        "role": "บทบาท", "mode": "โหมด", "tone": "น้ำเสียง",
        "input_label": "ป้อนหัวข้อหรือวางข้อความที่นี่...",
        "btn_submit": "✨ สร้างเนื้อหา",
        "btn_copy": "📋 คัดลอก",
        "btn_clear": "🗑️ ล้าง",
        "tab_main": "สร้าง AI",
        "tab_history": "ประวัติ",
        "tab_upgrade": "อัปเกรด Pro",
        "tab_help": "ช่วยเหลือ",
        "tbl_head": ["เปรียบเทียบ", "ผู้เยี่ยมชม (ฟรี)", "Pro (จ่ายเงิน)"],
        "upgrade_title": "ปลดล็อก Pro",
        "upgrade_btn": "รับคีย์",
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "แผนผู้เยี่ยมชม", "plan_pro": "แผน Pro",
        "usage": "การใช้งานรายวัน", "lang": "ภาษาอินเทอร์เฟซ",
        "faq_title": "ช่วยเหลือ", "quick_ans": "คำตอบด่วน", "sel_topic": "เลือกหัวข้อ",
        "submit_ticket": "ส่งตั๋ว", "type_lbl": "ประเภทตั๋ว",
        "issue_lbl": "อธิบายปัญหาหรือกด Enter...",
        "send_btn": "ส่ง", "logout": "รีเซ็ต / ออก",
        "action": "เลือกการกระทำ", "out_lang_lbl": "ภาษาผลลัพธ์", "tone_lbl": "น้ำเสียง",
        "generate": "✨ สร้างเนื้อหา",
        "lock_msg": "นี่คือคุณสมบัติ Pro โปรดอัปเกรด",
        "buy_btn": "👉 รับ Pro ทันที",
        "result": "ผลลัพธ์",
        "ad_copy": "1. คัดลอก", "ad_connect": "2. เครื่องมือ AI",
        "ad_social": "3. แชร์", "ad_manual": "4. โพสต์เอง",
        "ad_download": "5. บันทึกไฟล์", "ad_locked": "Pro เท่านั้น"
    },

    "Vietnamese": {
        "title": "PromptLab AI",
        "subtitle": "Kỹ sư Prompt AI Tự động của Bạn",
        "role": "Vai trò", "mode": "Chế độ", "tone": "Giọng văn",
        "input_label": "Nhập chủ đề hoặc dán văn bản vào đây...",
        "btn_submit": "✨ Tạo nội dung",
        "btn_copy": "📋 Sao chép",
        "btn_clear": "🗑️ Xóa",
        "tab_main": "Tạo AI",
        "tab_history": "Lịch sử",
        "tab_upgrade": "Nâng cấp Pro",
        "tab_help": "Hỗ trợ",
        "tbl_head": ["So sánh tính năng", "Khách (Miễn phí)", "Pro (Trả phí)"],
        "upgrade_title": "Mở khóa Pro",
        "upgrade_btn": "Mua Key",
        "sidebar_title": "Lai's Lab AI",
        "plan_guest": "Gói Khách", "plan_pro": "Gói Pro",
        "usage": "Sử dụng", "lang": "Ngôn ngữ",
        "faq_title": "Hỗ trợ & FAQ", "quick_ans": "Trả lời nhanh", "sel_topic": "Chọn chủ đề",
        "submit_ticket": "Gửi phiếu", "type_lbl": "Loại phiếu",
        "issue_lbl": "Mô tả vấn đề hoặc nhấn Enter...",
        "send_btn": "Gửi", "logout": "Đặt lại / Thoát",
        "action": "Chọn Hành động", "out_lang_lbl": "Ngôn ngữ đích", "tone_lbl": "Giọng văn",
        "generate": "✨ Tạo nội dung",
        "lock_msg": "Tính năng Pro. Vui lòng nâng cấp.",
        "buy_btn": "👉 Mua Pro ngay",
        "result": "Kết quả",
        "ad_copy": "1. Sao chép", "ad_connect": "2. Công cụ AI",
        "ad_social": "3. Chia sẻ", "ad_manual": "4. Thủ công",
        "ad_download": "5. Lưu tệp", "ad_locked": "Chỉ Pro"
    }
}

# ==========================================
# 核心函数: 获取UI字典 (Core Function)
# ==========================================
def get_safe_ui(lang):
    """
    Returns the UI dictionary for the specified language.
    Falls back to 'English' if the language is not found.
    Ensures no keys are missing by merging with English defaults.
    """
    base = UI_BUNDLE.get("English").copy() 
    target = UI_BUNDLE.get(lang, {})
    base.update(target) 
    return base
