# logic_core.py
# Lai's Lab V9.2 - 逻辑大脑 (最终纯净版)
# 负责：权限判断、Prompt组装、智能拦截、邮件自动化、Telegram通知、Airtable备份

import time
import requests
import smtplib
import random
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# 引入数据库
from data_matrix import ROLES_CONFIG, FAQ_DATABASE

# ==========================================
# 1. 核心配置区域 (Config Zone)
# ==========================================
# ⚠️ 注意：这里全部留空！
# 所有的密码和 Key 都会由 app.py 从 .streamlit/secrets.toml 读取并注入进来。

CONFIG = {
    # 邮件发送配置
    "EMAIL_SENDER_ADDRESS": "", # 会由 Secrets 注入
    "EMAIL_APP_PASSWORD": "",   # 会由 Secrets 注入
    
    # 管理员配置
    "EMAIL_ADMIN_ADDRESS": "",  # 会由 Secrets 注入
    "EMAIL_REPLY_TO": "support@laislab.com", # 公开配置
    
    # 外部服务 API
    "TELEGRAM_BOT_TOKEN": "",   # 会由 Secrets 注入
    "TELEGRAM_CHAT_ID": "",     # 会由 Secrets 注入
    "LEMONSQUEEZY_API_KEY": "", # 会由 Secrets 注入
    
    # Airtable 配置
    "AIRTABLE_API_KEY": "",     # 会由 Secrets 注入
    "AIRTABLE_BASE_ID": "",    
    "AIRTABLE_TABLE_TICKETS": "Tickets",
    "AIRTABLE_TABLE_USERS": "Users"
}

# ==========================================
# 2. 权限与用量逻辑 (Access & Quota)
# ==========================================

def check_user_tier(email, license_key=None):
    """
    验证用户身份。
    """
    if not license_key:
        return "Guest"
    
    # 模拟验证 (真实版这里可以调用 CONFIG["LEMONSQUEEZY_API_KEY"] 去查)
    # 目前演示逻辑：只要以 LAI- 开头或者是管理员码就过
    if license_key.startswith("LAI-") or license_key == "ADMIN-8888":
        # 激活成功，记录到 Airtable
        log_user_to_airtable(email, license_key, "Active")
        return "Pro"
    else:
        return "Invalid"

def check_daily_limit_by_email(email, user_tier, current_usage):
    """
    检查每日用量 (绑定 Email)
    返回: (是否允许生成, 剩余次数, 最大次数)
    """
    if user_tier == "Guest":
        max_limit = 5
    else:
        max_limit = 1000 # Pro 的防滥用软限 (FUP)
        
    if current_usage >= max_limit:
        return False, 0, max_limit
    
    remaining = max_limit - current_usage
    return True, remaining, max_limit

def check_mode_lock(user_tier, mode_name):
    """
    检查模式是否被锁
    逻辑：Mode 1 (Free) 对所有人开放，其他 Mode 对 Guest 锁住
    """
    if "Free" in mode_name:
        return False # 不锁
    
    if user_tier == "Pro":
        return False # Pro 不锁
        
    return True # Guest 锁住

def perform_logout():
    """执行登出清理逻辑"""
    return True

# ==========================================
# 3. 核心生成引擎 (The Engine)
# ==========================================

def get_guest_loading_messages():
    """Guest 专属：温柔的排队/加载提示词"""
    messages = [
        "🔄 Connecting to Shared Server (Guest Queue)...",
        "🐢 Warming up the AI engine...",
        "⏳ Validating request in the public queue...",
        "☕ Sipping coffee while we generate...",
        "💡 Pro Tip: Enterprise members skip this queue...",
        "✨ Refining the prompt structure..."
    ]
    return messages

def generate_ai_response_mock(role, mode, option_label, user_input, user_tier, language):
    """
    生成逻辑 (包含假进度控制)
    """
    # 1. 查找模板
    option_list = ROLES_CONFIG[role][mode]
    template = "Act as an expert."
    for opt in option_list:
        if opt["label"] == option_label:
            template = opt["template"]
            break
            
    # 2. 组装 Prompt
    final_prompt = template.replace("{input}", user_input)
    
    # 3. 进度条逻辑 (Guest 慢, Pro 快)
    delay_time = 0.8 if user_tier == "Pro" else 4.0
    
    # 4. 模拟生成结果
    output = f"""[System: Generated Prompt for {language}]\n\n{final_prompt}\n\n(Instruction: Copy this prompt into ChatGPT/Gemini to get the best result in {language}.)"""
    
    # 5. 水印逻辑
    if user_tier == "Guest":
        watermark = "\n\n" + "-"*30 + "\nGenerated by Lai's Lab (Free Version)\n💎 Upgrade to Pro for Unlimited Access & No Watermark"
        output += watermark
        
    return output, delay_time

# ==========================================
# 4. 智能客服与拦截 (Smart Support)
# ==========================================

def smart_intercept(subject):
    """
    FAQ 拦截逻辑 (覆盖 16 项 FAQ)
    """
    subject_lower = subject.lower()
    
    # 拦截词库映射
    intercept_map = {
        "refund": "Purchase & License",
        "money": "Purchase & License",
        "key": "Purchase & License",
        "lost": "Purchase & License",
        "pdf": "Technical Support",
        "font": "Technical Support",
        "limit": "Usage Limits",
        "quota": "Usage Limits",
        "share": "Privacy & Security",
        "slow": "Technical Support",
        "affiliate": "Business & Affiliate",
        "invoice": "Business & Affiliate",
        "receipt": "Business & Affiliate",
        "commercial": "Usage Limits",
        "offline": "Usage Limits"
    }
    
    for word, category in intercept_map.items():
        if word in subject_lower:
            faq_list = FAQ_DATABASE[category]
            # 简单返回该分类下的第一条，实际可优化
            best_match = faq_list[0] 
            return True, f"💡 **Smart Answer:**\n\n**Q: {best_match['q']}**\n**A:** {best_match['a']}"
            
    return False, None

# ==========================================
# 5. 自动化通知系统 (Automation)
# ==========================================

def log_user_to_airtable(email, key, status):
    """记录新激活用户到 Airtable"""
    if not CONFIG["AIRTABLE_API_KEY"]: return
    
    url = f"https://api.airtable.com/v0/{CONFIG['AIRTABLE_BASE_ID']}/{CONFIG['AIRTABLE_TABLE_USERS']}"
    headers = {
        "Authorization": f"Bearer {CONFIG['AIRTABLE_API_KEY']}",
        "Content-Type": "application/json"
    }
    data = {
        "fields": {
            "Email": email,
            "License Key": key,
            "Status": status,
            "Date": datetime.now().isoformat()
        }
    }
    try:
        requests.post(url, headers=headers, json=data)
        send_telegram_alert(f"💰 New Pro User!\nEmail: {email}\nKey: {key}")
    except:
        pass

def log_ticket_to_airtable(ticket_id, email, tier, subject):
    """记录工单到 Airtable"""
    if not CONFIG["AIRTABLE_API_KEY"]: return
    
    url = f"https://api.airtable.com/v0/{CONFIG['AIRTABLE_BASE_ID']}/{CONFIG['AIRTABLE_TABLE_TICKETS']}"
    headers = {
        "Authorization": f"Bearer {CONFIG['AIRTABLE_API_KEY']}",
        "Content-Type": "application/json"
    }
    data = {
        "fields": {
            "Ticket ID": str(ticket_id),
            "User Email": email,
            "Tier": tier,
            "Subject": subject,
            "Status": "Pending"
        }
    }
    try:
        requests.post(url, headers=headers, json=data)
    except:
        pass

def send_telegram_alert(message):
    """发送 Telegram 通知"""
    if not CONFIG["TELEGRAM_BOT_TOKEN"]: return
    
    url = f"https://api.telegram.org/bot{CONFIG['TELEGRAM_BOT_TOKEN']}/sendMessage"
    payload = {
        "chat_id": CONFIG["TELEGRAM_CHAT_ID"],
        "text": message
    }
    try:
        requests.post(url, json=payload)
    except:
        pass

def send_auto_reply_email(user_email, user_tier, ticket_id, issue_subject):
    """
    真实邮件发送 (SMTP)
    """
    sender = CONFIG["EMAIL_SENDER_ADDRESS"]
    password = CONFIG["EMAIL_APP_PASSWORD"]
    admin_email = CONFIG["EMAIL_ADMIN_ADDRESS"]
    reply_to = CONFIG["EMAIL_REPLY_TO"]
    
    if not sender or not password:
        return "Simulation: Email Config Missing"

    # 1. 区分 Guest/Pro 话术
    if user_tier == "Pro":
        email_subject = f"💎 [VIP Priority] Ticket #{ticket_id} - We are on it!"
        wait_time = "1 - 2 business days"
        queue_type = "VIP Priority Queue"
        greeting = "Dear Pro Member,"
    else:
        email_subject = f"[Ticket Received] Case #{ticket_id}"
        wait_time = "3 - 5 business days"
        queue_type = "Standard Queue"
        greeting = "Dear User,"

    # 2. 邮件正文
    body = f"""
{greeting}

We have received your support request regarding: "{issue_subject}".

------------------------------------------------
TICKET ID: #{ticket_id}
STATUS: {queue_type}
ESTIMATED REPLY: {wait_time}
------------------------------------------------

While you wait, please check the FAQ section in the sidebar. Many issues (like Lost Keys or PDF Fonts) can be solved instantly there.

If this issue is resolved, no further action is needed.
If you still need help, simply reply to this email.

Best Regards,
Lai's Lab Support Team
    """

    # 3. 构建邮件
    msg = MIMEMultipart()
    msg['From'] = f"Lai's Lab Support <{sender}>"
    msg['To'] = user_email
    msg['Subject'] = email_subject
    msg.add_header('Reply-To', reply_to)
    
    msg.attach(MIMEText(body, 'plain'))

    # 4. 发送过程
    try:
        server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        server.login(sender, password)
        
        # 发送给用户
        server.send_message(msg)
        
        # 通知管理员
        send_telegram_alert(f"🆘 New Ticket (#{ticket_id})\nUser: {user_email}\nSubject: {issue_subject}")
        
        server.quit()
        return "Email Sent Successfully"
    except Exception as e:
        print(f"SMTP Error: {e}")
        return f"Email Failed: {e}"
