# prompt_logic.py
# ==========================================
# PromptLab AI V7.3 Ultimate Edition
# 核心逻辑引擎 (Core Logic Engine)
# 包含: PASEC生成, PDF渲染, 数据库管理, 验证逻辑
# ==========================================

import json
import os
import datetime
import time
import requests
import base64
import re
from fpdf import FPDF

# 1. 商业限制常量 (The Paywall Matrix)
# ------------------------------------------
LIMITS = {
    "FREE": {
        "text_daily": 5,
        "image_daily": 3,
        "batch_size": 1,
        "can_access_all_modes": False,
        "show_watermark": True
    },
    "PRO": {
        "text_daily": 1000,  # Unlimited
        "image_daily": 200,   # Fair Use
        "batch_size": 50,
        "can_access_all_modes": True,
        "show_watermark": False
    }
}

# 2. 本地数据库与持久化 (Persistence)
# ------------------------------------------
DB_FILE = 'user_db.json'

def load_db():
    if not os.path.exists(DB_FILE):
        return {}
    try:
        with open(DB_FILE, 'r') as f:
            return json.load(f)
    except:
        return {}

def save_db(db):
    with open(DB_FILE, 'w') as f:
        json.dump(db, f, indent=4)

def get_user_usage(email):
    """获取用户今日用量，自动处理跨天重置"""
    db = load_db()
    today_str = str(datetime.date.today())
    
    if email not in db:
        db[email] = {"date": today_str, "text_count": 0, "image_count": 0}
        save_db(db)
        return db[email]
    
    # 检查是否跨天
    if db[email].get("date") != today_str:
        db[email] = {"date": today_str, "text_count": 0, "image_count": 0}
        save_db(db)
    
    return db[email]

def update_user_usage(email, usage_type="text", count=1):
    """更新用量"""
    db = load_db()
    today_str = str(datetime.date.today())
    
    if email not in db or db[email].get("date") != today_str:
        db[email] = {"date": today_str, "text_count": 0, "image_count": 0}
    
    if usage_type == "image":
        db[email]["image_count"] += count
    else:
        db[email]["text_count"] += count
        
    save_db(db)

# 3. 激活码验证 (LemonSqueezy Real API)
# ------------------------------------------
def validate_license_key(key):
    """
    验证 License Key。
    1. 检查后门 ADMIN-8888
    2. 调用 LemonSqueezy API
    """
    key = key.strip()
    if not key:
        return False
        
    # 后门 (方便测试)
    if key == "ADMIN-8888":
        return True
        
    # 真实 API 验证
    try:
        url = "https://api.lemonsqueezy.com/v1/licenses/activate"
        payload = {"license_key": key, "instance_name": "PromptLab_Web"}
        headers = {"Accept": "application/json"}
        
        response = requests.post(url, data=payload, headers=headers, timeout=5)
        data = response.json()
        
        # 只要 activated 为 True 即视为成功
        if data.get("activated") is True:
            return True
    except:
        # 如果网络不通，但 Key 格式看起来像 PRO，为了不卡住用户，可以放行(可选)
        # 这里严格一点，只返回 False
        pass
        
    return False

# 4. PASEC 核心生成引擎 (The Brain)
# ------------------------------------------
def generate_pasec_prompt(role, mode, option, user_input, upload_count, language, is_pro):
    """
    生成符合 PASEC 结构的 Prompt。
    """
    # 1. 确定水印
    watermark = ""
    if not is_pro:
        watermark = "\n\n---\n🔒 [Trial Version] Generated by PromptLab AI (Free)"

    # 2. 根据选项构建内容 (Mock Logic)
    # 这里模拟 AI 的思考过程，实际上是根据模板填空
    
    context_str = f"User Input: {user_input}"
    if upload_count > 0:
        context_str += f"\n[System] Analyzed {upload_count} uploaded reference files."

    # 3. 组装 PASEC 结构
    # 强制包含 5 大标题
    
    prompt_content = f"""# Generated Prompt ({language})

## 👤 P - Persona (角色)
**Role**: {role}
**Mode**: {mode}
**Tone**: Professional & Engaging
**Language**: Target Output in {language}

## 🎯 A - Aim (目标)
**Task**: Execute specific task based on option "{option}".
**Goal**: Create high-quality content that meets professional standards.

## 📂 S - Structure (格式)
**Output Format**: Markdown
**Layout**: Logical flow with clear headings and bullet points.

## 📝 E - Effective (限制)
**Constraints**: 
- Avoid unnecessary fluff.
- Maintain strict adherence to the requested tone.
- Ensure cultural relevance for {language} audience.

## 💡 C - Context (情境)
{context_str}

---
**[AI Generation Start]**

(Here, the AI would generate the specific content for "{option}"...)

Based on your request "{user_input}", here is the draft:

1. **Core Concept**: Focusing on the key elements of {option}.
2. **Details**: Expanding on the topic with depth and clarity.
3. **Actionable Steps**: 
   - Step 1: Analyze the requirements.
   - Step 2: Apply the {mode} framework.
   - Step 3: Review and refine.

*(End of Generation)*{watermark}
"""
    return prompt_content

# 5. PDF 生成器 (带防崩溃机制)
# ------------------------------------------
def create_pdf_bytes(content):
    """
    将文本转换为 PDF 二进制流。
    包含字体回退逻辑。
    """
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    font_path = 'font.ttf'
    has_custom_font = False
    
    # 尝试加载中文字体
    if os.path.exists(font_path):
        try:
            pdf.add_font('CustomFont', '', font_path, uni=True)
            pdf.set_font('CustomFont', '', 12)
            has_custom_font = True
        except:
            pass
            
    # 如果没有字体，回退到 Arial 并过滤非拉丁字符
    if not has_custom_font:
        pdf.set_font("Arial", size=12)
        pdf.set_text_color(255, 0, 0)
        pdf.cell(0, 10, txt="[System Warning: 'font.ttf' not found. CJK characters removed.]", ln=True)
        pdf.set_text_color(0, 0, 0)
        
        # 简单的过滤逻辑，只保留 Latin-1 字符，防止报错
        safe_content = content.encode('latin-1', 'ignore').decode('latin-1')
        pdf.multi_cell(0, 10, txt=safe_content)
    else:
        # 有字体，直接输出
        pdf.multi_cell(0, 10, txt=content)
        
    return pdf.output(dest='S').encode('latin-1')

# 6. 智能工单拦截逻辑
# ------------------------------------------
def check_ticket_intercept(subject, message):
    """
    检查是否包含拦截关键词。
    返回: (should_intercept, reply_message)
    """
    full_text = (subject + " " + message).lower()
    
    # 关键词库
    refund_words = ["refund", "money back", "return", "cancel"]
    key_words = ["key", "license", "code", "lost", "invalid"]
    
    if any(w in full_text for w in refund_words):
        return True, "🚫 **Policy Notice**: As stated in our FAQ, digital products are **Non-Refundable**. Please check the 'Billing' section."
        
    if any(w in full_text for w in key_words):
        return True, "💡 **AI Suggestion**: Lost your key? You can recover it instantly at [LemonSqueezy Orders](https://app.lemonsqueezy.com/my-orders)."
        
    return False, None